feat: 페이징 처리 기능 추가
woorifisa-service-dev-3rd/backend-2nd-PetMily pull request #10
Opened 2024-09-07 00:15 UTC by qbobl5

- 가맹점 조회 시 페이징 처리
- 거래내역 조회 시 페이징 처리

2024-09-07 00:23 UTC, hcu55 requested changes
페이징 처리 기능에 대해 배워갑니다~

2024-09-07 00:24 UTC, hcu55 approved these changes
확인했습니다!

2024-09-07 00:53 UTC, rlfrkdms1 commented on src/main/java/woori/petmily_card/controller/HospitalController.java
>      public String showHospitals(@PathVariable(value = "page") int page, Model model) {
page를 쿼리파라미터각 아닌 `PathVariable`로 받은 이유가 있나요 ?

2024-09-07 00:53 UTC, rlfrkdms1 commented on src/main/java/woori/petmily_card/service/HospitalServiceImpl.java
> +        return hospitals.map(HospitalResponse::from);
음 Page를 사용한 이유는 `page`, `totalPages`때문인 것으로 보이는데 이를 담은 Response를 만들어서 사용하지 않고 그냥 Page로 반환하는 이유가 있나요?

2024-09-07 00:53 UTC, rlfrkdms1 commented on src/main/java/woori/petmily_card/service/TransactionServiceImpl.java
> +                transaction -> TransactionResponse.of(transaction.getAmount(), transaction.getHospital()));
어차피 transation의 요소를 파라미터로 of가 받는데, 그럴거면 transation 하나를 받는 from을 쓰는게 더 좋을 것 같습니다

2024-09-12 00:09 UTC, qbobl5 commented on src/main/java/woori/petmily_card/service/TransactionServiceImpl.java
> +                transaction -> TransactionResponse.of(transaction.getAmount(), transaction.getHospital()));
오 좋습니다

2024-09-12 00:22 UTC, qbobl5 commented on src/main/java/woori/petmily_card/controller/HospitalController.java
>      public String showHospitals(@PathVariable(value = "page") int page, Model model) {
이건 이번에 컨트롤러 수정하면서 바꿀 예정입니다~~!

2024-09-12 00:22 UTC, qbobl5 commented on src/main/java/woori/petmily_card/service/HospitalServiceImpl.java
> +        return hospitals.map(HospitalResponse::from);
이건 제가 Page 를 첨써봐서 ㅎㅎ... ㅜ 더 공부해보도록 하겠숨다

2024-09-12 00:23 UTC, merged